spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 465
    username: mygmail
    password: mypassword
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: "*"
            enable: true
          starttls:
            enable: true
    protocol: smtp


application:
  security:
    jwt:
      secret-key: 69abe6b406c6996073e22f19751908aee434644809fe0eebb9a17e6420746bc5
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      photos-output-path: ./upload
  google:
    clientId: 897840734961-7mmsjme05o2av1c15q9rlhak755leg74.apps.googleusercontent.com
server:
  port: 8088